version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    labels: ["dependencies"]
    commit-message:
      prefix: "chore: deps"
    groups:
      go-dependencies:
        patterns: ["*"]

  - package-ecosystem: "github-actions"
    directories:
      - "/.github/**"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    labels: ["dependencies"]
    commit-message:
      prefix: "chore: deps"
    groups:
      actions:
        patterns: ["*"]

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    labels: ["dependencies"]
    commit-message:
      prefix: "chore: deps"
    groups:
      docker:
        patterns: ["*"]

  - package-ecosystem: "terraform"
    directories:
      - "/provider/eks/terraform"
      - "/provider/gke/terraform"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    labels: ["dependencies"]
    commit-message:
      prefix: "chore: deps"
    groups:
      terraform-providers:
        patterns: ["*"]
