#!/usr/bin/env bash

DIR="$(dirname "$0")"
. "${DIR}/env"


# Create a pod to test the PVC
kubectl apply -f - <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: ebs-test-pod
spec:
  containers:
  - name: test
    image: ubuntu
    command: ["/bin/bash"]
    args: ["-c", "while true; do echo $(date -u) >> /data/test.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-pvc
EOF

# Wait for the pod to be running
kubectl get pods --watch

# Run few tests 
kubectl exec -ti ebs-test-pod -- df -h
kubectl exec -it ebs-test-pod -- more /data/test.txt
kubectl exec -it ebs-test-pod -- whoami

# cleanup
kubectl delete pod ebs-test-pod
