apiVersion: github.com/mchmarny/cluster/v1alpha1
kind: Cluster

deployment:
  id: mini-gpu
  provider: gke
  tenancy: eidosx
  location: us-central1
  state: tenancy
  destroy: false
  tags:
    env: demo

cluster:
  gke:
    version: "1.35"
    controlPlane:
      authorizedNetworks:
        - cidr: 216.228.127.128/30
          name: hq
        - cidr: 52.41.222.58/32
          name: nw1
        - cidr: 54.68.11.139/32
          name: nw2

compute:
  gke:
    nodePools:
      system:
        machineType: e2-standard-4
        autoscaling:
          enabled: true
          minNodes: 1
          maxNodes: 3

      workers:
        - name: cpu-worker
          machineType: n2-standard-8
          diskType: pd-ssd
          diskSizeGb: 200
          zones:
            - us-central1-c
          autoscaling:
            enabled: true
            minNodes: 1
            maxNodes: 1
          nodeConfig:
            labels:
              nodeGroup: cpu-worker
        - name: gpu-worker
          machineType: a3-megagpu-8g
          diskType: pd-ssd
          diskSizeGb: 200
          zones:
            - us-central1-a
          autoscaling:
            enabled: true
            minNodes: 2
            maxNodes: 2
          guestAccelerator:
            type: nvidia-h100-mega-80gb
            count: 8
            gpuDriverInstallation:
              gpuDriverVersion: DEFAULT
          # hostMaintenancePolicy:
          #   maintenanceInterval: PERIODIC
          nodeConfig:
            gvnic: true
            capacityReservations:
              - projects/nv-dgxcloudprod-20240108/reservations/h100-a3-mega-phase-1-general-pool-384-us-c1-reservation
            taints:
              - key: dedicated
                value: gpu-workload
                effect: NO_SCHEDULE
            labels:
              nodeGroup: gpu-worker
