apiVersion: github.com/mchmarny/cluster/v1alpha1
kind: Cluster

deployment:
  id: mini-cpu
  provider: gke
  tenancy: eidosx
  location: us-central1
  state: tenancy
  destroy: false
  tags:
    env: demo

cluster:
  gke:
    version: "1.35"
    controlPlane:
      authorizedNetworks:
        - cidr: 216.228.127.128/30
          name: hq
        - cidr: 52.41.222.58/32
          name: nw1
        - cidr: 54.68.11.139/32
          name: nw2

compute:
  gke:
    nodePools:
      system:
        machineType: e2-standard-4
        autoscaling:
          enabled: true
          minNodes: 1
          maxNodes: 3

      workers:
        - name: cpu-worker
          machineType: n2-standard-8
          diskType: pd-ssd
          diskSizeGb: 200
          autoscaling:
            enabled: true
            minNodes: 1
            maxNodes: 1
          nodeConfig:
            labels:
              nodeGroup: cpu-worker
