apiVersion: github.com/mchmarny/cluster/v1alpha1
kind: Cluster

deployment:
  id: min-cpu
  provider: gke
  tenancy: "my-gcp-project"
  location: us-west1
  state: tenancy
  destroy: false
  tags:
    env: demo
    stack: mini

cluster:
  gke:
    version: "1.33"
    releaseChannel: STABLE

compute:
  gke:
    nodePools:
      system:
        machineType: e2-standard-4
      workers:
        - name: cpu-worker-1
          machineType: n2-standard-8
          labels:
            nodeGroup: cpu-worker
