name: terraform-validate

on:
  push:
    branches: [ main ]
  pull_request:
    paths:
      - '**/*.tf'
      - '**/*.tfvars'
      - '**/.terraform.lock.hcl'

permissions:
  contents: read

env:
  TF_VERSION: "1.13.4"
  TF_IN_AUTOMATION: "true"
  TF_INPUT: "false"
  TF_PLUGIN_CACHE_DIR: "~/.terraform.d/plugin-cache"
  SCAN_SEVERITY: "HIGH,CRITICAL"

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      id-token: write

    steps:

      # Checkout Code Step
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0

      # Trivy IaC Scan Steps
      - name: Trivy IaC scan (Terraform)
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8  # v0.33.1
        with:
          scan-type: 'config'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: '${{ env.SCAN_SEVERITY }}'
          exit-code: '0'
          trivyignores: '.trivyignore'

      - name: Upload Report
        uses: github/codeql-action/upload-sarif@16df4fbc19aea13d921737861d6c622bf3cefe23  # v2.23.0
        with:
          sarif_file: 'trivy-results.sarif'

      # Terraform Validation Steps
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd  # v3.1.2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Create Terraform plugin cache directory
        run: mkdir -p ~/.terraform.d/plugin-cache

      - name: Cache Terraform plugin directory
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830  # v4.3.0
        with:
          path: ~/.terraform.d/plugin-cache
          key: tf-plugins-${{ runner.os }}-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            tf-plugins-${{ runner.os }}-

      - name: Install TFLint
        uses: terraform-linters/setup-tflint@acd1575d3c037258ce5b2dd01379dc49ce24c6b7  # v6.2.0

      - name: Terraform init
        run: make tf-init

      - name: Terraform validate (per directory)
        shell: bash
        run: make tf-validate

      - name: Terraform fmt (check)
        run: make tf-fmt

      - name: TFLint (recursive)
        run: make tf-lint